apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: kube-system
  name: toy-scheduler-sa
  labels:
    app: toy-scheduler
    component: toy-scheduler
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: toy-scheduler
subjects:
- kind: ServiceAccount
  name: toy-scheduler-sa
  namespace: kube-system 
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: system:kube-scheduler
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    component: kube-scheduler
    tier: control-plane
    app: toy-scheduler
  name: toy-scheduler
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: toy-scheduler
  template:
    metadata:
      labels:
        app: toy-scheduler
        component: kube-scheduler
        tier: control-plane
    spec:
      containers:
      - image: yipengh/toy-scheduler:devel
        name: toy-scheduler
        resources:
          requests:
            cpu: 100m
      priorityClassName: system-node-critical
      serviceAccount: toy-scheduler-sa
