apiVersion: v1
kind: Pod
metadata:
  labels:
    component: kube-scheduler
    tier: control-plane
  name: toy-scheduler
  namespace: kube-system
spec:
  containers:
  - image: yipengh/toy-scheduler:devel
    imagePullPolicy: Always
    name: toy-scheduler
    resources:
      requests:
        cpu: 100m
    volumeMounts:
    - mountPath: /root/.kube/config
      name: kubeconfig
      readOnly: true
  priorityClassName: system-node-critical
  volumes:
  - hostPath:
      path: /etc/kubernetes/scheduler.conf
      type: FileOrCreate
    name: kubeconfig
